[package]
name = "tikv"
version = "1.1.0-dev.1"
keywords = ["KV", "distributed-systems", "raft"]
build = "build.rs"

[build-dependencies]
time = "0.1"

[features]
default = []
dev = ["clippy"]
portable = ["rocksdb/portable"]
sse = ["rocksdb/sse"]
mem-profiling = ["jemallocator"]
no-fail = ["fail/no_fail"]

[lib]
name = "tikv"

[[bin]]
name = "tikv-server"

[[bin]]
name = "bench-tikv"
path = "benches/bin/bench-tikv.rs"

[[bin]]
name = "tikv-ctl"

[[bin]]
name = "tikv-fail"

[dependencies]
log = "0.3"
byteorder = "0.5"
rand = "0.3"
quick-error = "0.2"
tempdir = "0.3"
time = "0.1"
toml = "0.4"
libc = "0.2"
crc = "1.2"
fs2 = "0.4"
clippy = {version = "*", optional = true}
protobuf = "1.4"
nix = "0.9.0"
utime = "0.2"
chrono = "0.4"
lazy_static = "0.2.1"
backtrace = "0.2.3"
clap = "2"
url = "1.5"
regex = "0.1"
fnv = "1.0"
sys-info = "0.5.1"
flat_map = "0.0.4"
ordermap = "0.3"
mio = "0.5"
futures = "0.1"
futures-cpupool = "0.1"
tokio-core = "0.1"
tokio-timer = "0.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
rustc-serialize = "0.3"
murmur3 = "0.4.0"
zipf = "0.2.0"
bitflags = "1.0.1"
fail = "0.2"
uuid = { version = "0.4", features = [ "serde", "v4" ] }

[target.'cfg(unix)'.dependencies]
signal = "0.4"

[dependencies.rocksdb]
git = "https://github.com/pingcap/rust-rocksdb.git"

[dependencies.kvproto]
git = "https://github.com/pingcap/kvproto.git"

[dependencies.tipb]
git = "https://github.com/pingcap/tipb.git"

[dependencies.prometheus]
version = "0.3"
default-features = false
features = ["nightly", "push", "process"]

[dependencies.jemallocator]
git = "https://github.com/busyjay/jemallocator.git"
branch = "dev"
features = ["profiling"]
optional = true

[dependencies.grpcio]
version = "0.2"
features = ["secure"]

[replace]
"protobuf:1.4.1" = { git = "https://github.com/stepancheg/rust-protobuf.git" }

[profile.dev]
opt-level = 0  # Controls the --opt-level the compiler builds with
debug = true   # Controls whether the compiler passes `-g`
codegen-units = 4

# The release profile, used for `cargo build --release`
[profile.release]
lto = true
opt-level = 3
debug = true
